### ISSUE TITLE
Bad substitution when dash is used for sh

### ISSUE THREAD

**Issue by CharlesGueunet** [Delapouite/kakoune-buffers#16] opened 2020-09-30 08:52 UTC
Hello,

First of all, thanks for this nice plugin.
I have use dash as my `/bin/sh` as dash is POSIX compliant but way faster than bash.
I seems however that this break the `pick-buffer` command. The list of buffer stay empty and the debug buffer tells me:
```
shell stedrr: <<<
sh: 16: Bad substitution
>>>
```

We may want to explicitely use `#!/bin/bash` or to use a POSIX compliant substitution instead.

I am writing this quickly, I will take more time to investigate when I can.

Charles

**Comment by cmusser** [comment] 2021-04-02 15:16
Right, it fails because the `${parameter:offset:length}` is a bash/ksh construct. #19 fixes this by using the cut command to do the string array slicing that produces the buffer id.

**Comment by cmusser** [comment] 2021-04-12 23:48
now that #18 and #19 are merged, this works better. Can you test and see if it works for you as well?

**Comment by vollia** [comment] 2021-04-13 06:52
Yep, this works as intended now :)  
Thanks a lot !

**Closed as completed by vollia** 2021-04-13 06:52 UTC
Labels: bug
